### ISSUE TITLE
feat/app-create-post-screen

### ISSUE THREAD

**Issue by Veryyapeee** [coders-camp-2021-best-team/TeamUp-Client#29]
**AC**

Implement UI based on Figma ~ https://www.figma.com/file/RkzObeqWU4mYZwuYVnnPOC/TeamUp?node-id=52356%3A15451

Connect screen to API:
- [x] Fetch posts
- [x] Run request to submit opinion (like/dislike)

**Comment by maciejopalinski** [comment]
@Mariusz-web it's not completed yet
