### ISSUE TITLE
feat/app-create-post-details-screen

### ISSUE THREAD

**Issue by Veryyapeee** [coders-camp-2021-best-team/TeamUp-Client#30]
**AC**

Create PostDetailScreen based on figma ~ https://www.figma.com/file/RkzObeqWU4mYZwuYVnnPOC/TeamUp?node-id=52417%3A16310

Implement API connection ~ just fetching the post details with comments

**Comment by maciejopalinski** [comment]
We don't have post comments xD
/closing
